language: java
sudo: false
jdk:
  - oraclejdk8
script: 
        - mvn clean test -DCACHE=true -Dtest=CacheTest -B
        - mvn clean test -B
        - mvn clean test -DCACHE=true -Dtest=CacheTest -P mybatis-327 -B
        - mvn clean test -P mybatis-327 -B
        - mvn clean test -DCACHE=true -Dtest=CacheTest -P mybatis-328 -B
        - mvn clean test -P mybatis-328 -B
        - mvn jacoco:report
        - pip install --user codecov
install: 
        mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B       
after_success: 
  - codecov
branches: 
  only:
    - ForMybatis3.2.6-3.2.8